logo: doc/assest/Studio Pic.JPG
title: Ugochi Uchenna
tagline: Data Analyst | SQL Developer 
description: SQL Developer | Data Analyst 
Social Media: [doc/assest/email icon.jpg](ugochifavour123@gmail.com) | 
theme: jekyll-theme-minimal-mistakes
