title: Ugochi Uchenna
logo: doc/assest/Studio Pic.JPG
tagline: Data Analyst | SQL Developer 
description: SQL Developer | Data Analyst 
#show_downloads: True
author:
  name: Ugochi Uchenna
  email: ugochifavour123@gmail.com
theme: jekyll-theme-minimal
