logo: doc/assest/Studio Pic.JPG
title: Ugochi Uchenna
tagline: Data Analyst | SQL Developer 
description: SQL Developer | Data Analyst 
Social Media: [doc/assest/email icon.jpg](ugochifavour123@gmail.com) | [doc/assest/Linkedin icon.png](https://www.linkedin.com/in/ugochi-ugoala-dc/)
theme: jekyll-theme-minimal-mistakes
